version: '3'

services:
    frontend:
        build: './Frontend'
        image: 'groupfinder/client'
        container_name: 'groupfinderClientContainer'
        ports:
            - "3000:3000"
        volumes:
            - ./Frontend/Groupfinder:/usr/src/nuxt-app
            - /usr/src/nuxt-app/node_modules
    backend:
        build: './Backend'
        image: 'groupfinder/server'
        container_name: 'groupfinderServerContainer'
        depends_on:
            - db
        ports:
            - "4000:4000"
        volumes:
            - ./Backend/Groupfinder:/usr/src/app
            - /usr/src/app/node_modules
    db:
        build: './Database'
        image: 'groupfinder/database'
        container_name: 'groupfinderDatabaseContainer'
        ports: 
            - '3306:3306/tcp'
        volumes:
            - 'data:/var/lib/mysql'

volumes:
    'data':