version: '3'

services:
    frontend:
        build: './Frontend'
        image: '${FRONTEND_IMAGE}'
        container_name: '${FRONTEND_CONTAINER}'
        ports:
            - "${FRONTEND_PORT}:${FRONTEND_PORT}"
        volumes:
            - ./Frontend/Groupfinder:/usr/src/nuxt-app
            - /usr/src/nuxt-app/node_modules
        environment:
            - API_PORT=:${BACKEND_PORT}/

    backend:
        build: './Backend'
        image: '${BACKEND_IMAGE}'
        container_name: '${BACKEND_CONTAINER}'
        ports:
            - "${BACKEND_PORT}:${BACKEND_PORT}"
        volumes:
            - ./Backend/Groupfinder:/usr/src/app
            - /usr/src/app/node_modules
    db:
        build: './Database'
        image: '${DB_IMAGE}'
        container_name: '${DB_CONTAINER}'
        ports: 
            - '${DB_PORT}:${DB_PORT}'
        volumes:
            - 'data:/var/lib/mysql'

volumes:
    'data':